DROP INDEX IF EXISTS idx_users_team_id;
ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_team_by_role;
ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_role;
ALTER TABLE users ALTER COLUMN role SET DEFAULT 'user';
ALTER TABLE users DROP COLUMN IF EXISTS is_active;
ALTER TABLE users DROP COLUMN IF EXISTS team_id;
