/**
 * GENERATED FILE — do not hand-edit, it will be overwritten on regen.
 *
 * Backend still emits Swagger 2.0 (backend/docs/swagger.json), and
 * openapi-typescript needs OpenAPI 3, so regen is a two-step pipeline
 * run from `frontend/`:
 *
 *   npx swagger2openapi ../backend/docs/swagger.json -o ./openapi3.json
 *   npx openapi-typescript ./openapi3.json -o src/api/types.ts
 *   rm openapi3.json
 *
 * Run this whenever backend endpoints/DTOs change. If a type here
 * doesn't match what you need, the fix is in the backend/Swagger
 * annotations, not in this file.
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Login request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.LoginInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.TokenResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout from all devices */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Refresh token (optional if cookie present) */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["dto.RefreshTokenInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.TokenResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List leads */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.PaginatedLeadResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create lead */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Create lead */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.CreateLeadInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.LeadResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get lead */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Lead code */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.LeadResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update lead */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Lead code */
                    code: string;
                };
                cookie?: never;
            };
            /** @description Update lead */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.UpdateLeadInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.LeadResponse"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/leads/{code}/followups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List follow-ups */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Lead code */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.FollowUpResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create follow-up */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Lead code */
                    code: string;
                };
                cookie?: never;
            };
            /** @description Create follow-up */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.CreateFollowUpInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.FollowUpResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{code}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update lead status */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Lead code */
                    code: string;
                };
                cookie?: never;
            };
            /** @description Update lead status */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.UpdateLeadStatusInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.LeadResponse"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/refs/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cities by province */
        get: {
            parameters: {
                query: {
                    /** @description Province ID */
                    province_id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.CityResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refs/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List districts by city */
        get: {
            parameters: {
                query: {
                    /** @description City ID */
                    city_id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.DistrictResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refs/lead-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active lead sources */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.LeadSourceResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refs/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List provinces */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.ProvinceResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refs/service-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active service types */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.ServiceTypeResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refs/villages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List villages by district */
        get: {
            parameters: {
                query: {
                    /** @description District ID */
                    district_id: number;
                    /** @description Name search */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.VillageResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sales teams */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.TeamResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create sales team */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Create team */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.CreateTeamInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.TeamResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get sales team */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Team ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.TeamResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update sales team */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Team ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update team */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.UpdateTeamInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.TeamResponse"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (LEADER: own team roster; ADMIN_SALES/SU: unrestricted) */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by role */
                    role?: string;
                    /** @description Filter by team id (ignored for LEADER callers, who are always scoped to their own team) */
                    team_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.UserResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create user (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Create user */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.CreateUserInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.UserResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.UserResponse"];
                        };
                    };
                };
            };
        };
        /** Update profile */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Update profile */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.UpdateProfileInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.UserResponse"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by id (admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.UserResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user (admin only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update user */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.UpdateUserInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.UserResponse"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate a user (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Deactivate user */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.DeactivateUserInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"];
                    };
                };
                /** @description user still has active leads, reassign_to_user_id required */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a user's password (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Reset password */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.ResetPasswordInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "dto.CityResponse": {
            id?: number;
            name?: string;
        };
        "dto.CreateFollowUpInput": {
            note: string;
        };
        "dto.CreateLeadInput": {
            business_field?: string;
            capacity_mbps?: number;
            city_id?: number;
            company_name: string;
            district_id?: number;
            email?: string;
            existing_isp?: string;
            lead_source_id?: string;
            mobile_phone?: string;
            office_phone?: string;
            other_services?: string;
            owner_id?: string;
            pic_name?: string;
            pic_position?: string;
            price?: number;
            province_id?: number;
            rt?: string;
            rw?: string;
            service_type_id?: string;
            street?: string;
            village_id?: number;
            website?: string;
            zip_id?: number;
        };
        "dto.CreateTeamInput": {
            name: string;
        };
        "dto.CreateUserInput": {
            email: string;
            name: string;
            password: string;
            /** @enum {string} */
            role: "SALES" | "LEADER" | "ADMIN_SALES" | "SU";
            team_id?: string;
        };
        "dto.DeactivateUserInput": {
            reassign_to_user_id?: string;
        };
        "dto.DistrictResponse": {
            id?: number;
            name?: string;
        };
        "dto.FollowUpResponse": {
            created_at?: string;
            created_by_id?: string;
            id?: string;
            lead_id?: string;
            note?: string;
        };
        "dto.LeadResponse": {
            business_field?: string;
            capacity_mbps?: number;
            city_id?: number;
            city_name?: string;
            code?: string;
            company_name?: string;
            created_at?: string;
            created_by_id?: string;
            district_id?: number;
            email?: string;
            existing_isp?: string;
            follow_up_count?: number;
            id?: string;
            is_stale?: boolean;
            last_follow_up_at?: string;
            lead_source_id?: string;
            lost_reason?: string;
            mobile_phone?: string;
            office_phone?: string;
            other_services?: string;
            owner_id?: string;
            owner_name?: string;
            pic_name?: string;
            pic_position?: string;
            price?: number;
            province_id?: number;
            rt?: string;
            rw?: string;
            service_type_id?: string;
            status?: string;
            street?: string;
            village_id?: number;
            website?: string;
            zip_id?: number;
        };
        "dto.LeadSourceResponse": {
            id?: string;
            name?: string;
        };
        "dto.LoginInput": {
            email: string;
            password: string;
        };
        "dto.PaginatedLeadResponse": {
            items?: components["schemas"]["dto.LeadResponse"][];
            limit?: number;
            page?: number;
            total?: number;
        };
        "dto.ProvinceResponse": {
            code?: string;
            id?: number;
            name?: string;
        };
        "dto.RefreshTokenInput": {
            refresh_token?: string;
        };
        "dto.ResetPasswordInput": {
            new_password: string;
        };
        "dto.ServiceTypeResponse": {
            id?: string;
            name?: string;
        };
        "dto.TeamResponse": {
            created_at?: string;
            id?: string;
            is_active?: boolean;
            name?: string;
        };
        "dto.TokenResponse": {
            access_token?: string;
            refresh_token?: string;
            user?: components["schemas"]["dto.UserResponse"];
        };
        "dto.UpdateLeadInput": {
            business_field?: string;
            capacity_mbps?: number;
            city_id?: number;
            company_name?: string;
            district_id?: number;
            email?: string;
            existing_isp?: string;
            lead_source_id?: string;
            mobile_phone?: string;
            office_phone?: string;
            other_services?: string;
            owner_id?: string;
            pic_name?: string;
            pic_position?: string;
            price?: number;
            province_id?: number;
            rt?: string;
            rw?: string;
            service_type_id?: string;
            street?: string;
            village_id?: number;
            website?: string;
            zip_id?: number;
        };
        "dto.UpdateLeadStatusInput": {
            lost_reason?: string;
            /** @enum {string} */
            status: "FOLLOW_UP" | "HANDOFF_ODOO" | "LOST";
        };
        "dto.UpdateProfileInput": {
            name: string;
        };
        "dto.UpdateTeamInput": {
            is_active?: boolean;
            name?: string;
        };
        "dto.UpdateUserInput": {
            name?: string;
            /** @enum {string} */
            role?: "SALES" | "LEADER" | "ADMIN_SALES" | "SU";
            team_id?: string;
        };
        "dto.UserResponse": {
            created_at?: string;
            email?: string;
            id?: string;
            is_active?: boolean;
            name?: string;
            role?: string;
            team_id?: string;
        };
        "dto.VillageResponse": {
            id?: number;
            name?: string;
            zip?: components["schemas"]["dto.ZipResponse"];
        };
        "dto.ZipResponse": {
            code?: string;
            id?: number;
        };
        "utils.Response": {
            data?: unknown;
            errors?: unknown;
            message?: string;
            success?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
