/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Login request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.LoginInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.TokenResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout from all devices */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Refresh token (optional if cookie present) */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["dto.RefreshTokenInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.TokenResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard activity trend (lead baru vs follow-up per day) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.DashboardActivityResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/sales-activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard sales activity ("Keaktifan Sales") - LEADER/ADMIN_SALES/SU only */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.DashboardSalesActivityResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard segments (sumber, wilayah, kompetitor, bidang usaha) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.DashboardSegmentsResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/stale-leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard stale (terlantar) leads */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.DashboardStaleLeadsResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard summary (metric cards + funnel) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.DashboardSummaryResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lead-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all lead sources, active and inactive (admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.LeadSourceAdminResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create lead source (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Create lead source */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.CreateLeadSourceInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.LeadSourceAdminResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lead-sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update lead source (admin only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Lead source ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update lead source */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.UpdateLeadSourceInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.LeadSourceAdminResponse"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List leads */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.PaginatedLeadResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create lead */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Create lead */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.CreateLeadInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.LeadResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export leads to Excel */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Caller's own account password */
                    "X-Export-Password": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get lead */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Lead code */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.LeadDetailResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update lead */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Lead code */
                    code: string;
                };
                cookie?: never;
            };
            /** @description Update lead */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.UpdateLeadInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.LeadResponse"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/leads/{code}/followups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List follow-ups */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Lead code */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.FollowUpResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create follow-up */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Lead code */
                    code: string;
                };
                cookie?: never;
            };
            /** @description Create follow-up */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.CreateFollowUpInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.FollowUpResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{code}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update lead status */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Lead code */
                    code: string;
                };
                cookie?: never;
            };
            /** @description Update lead status */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.UpdateLeadStatusInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.LeadResponse"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/refs/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cities by province */
        get: {
            parameters: {
                query: {
                    /** @description Province ID */
                    province_id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.CityResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refs/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List districts by city */
        get: {
            parameters: {
                query: {
                    /** @description City ID */
                    city_id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.DistrictResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refs/lead-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active lead sources */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.LeadSourceResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refs/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List provinces */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.ProvinceResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refs/service-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active service types */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.ServiceTypeResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refs/villages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List villages by district */
        get: {
            parameters: {
                query: {
                    /** @description District ID */
                    district_id: number;
                    /** @description Name search */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.VillageResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all service types, active and inactive (admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.ServiceTypeAdminResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create service type (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Create service type */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.CreateServiceTypeInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.ServiceTypeAdminResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update service type (admin only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Service type ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update service type */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.UpdateServiceTypeInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.ServiceTypeAdminResponse"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sales teams */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.TeamResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create sales team */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Create team */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.CreateTeamInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.TeamResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get sales team */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Team ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.TeamResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update sales team */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Team ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update team */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.UpdateTeamInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.TeamResponse"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (LEADER: own team roster; ADMIN_SALES/SU: unrestricted) */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by role; comma-separated for multiple (e.g. SALES,LEADER) */
                    role?: string;
                    /** @description Filter by team id (ignored for LEADER callers, who are always scoped to their own team) */
                    team_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.UserResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create user (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Create user */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.CreateUserInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.UserResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.UserResponse"];
                        };
                    };
                };
            };
        };
        /** Update profile */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Update profile */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.UpdateProfileInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.UserResponse"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by id (admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.UserResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user (admin only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update user */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.UpdateUserInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"] & {
                            data?: components["schemas"]["dto.UserResponse"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate a user (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Deactivate user */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.DeactivateUserInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"];
                    };
                };
                /** @description user still has active leads, reassign_to_user_id required */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a user's password (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Reset password */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.ResetPasswordInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["utils.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "dto.ActivityBucket": {
            /** @description YYYY-MM-DD */
            date?: string;
            follow_up?: number;
            lead_baru?: number;
        };
        "dto.CityResponse": {
            id?: number;
            name?: string;
        };
        "dto.CompetitorStats": {
            avg_price_per_mbps?: number;
            avg_price_per_mbps_broadband?: number;
            avg_price_per_mbps_dedicated?: number;
        };
        "dto.CreateFollowUpInput": {
            note: string;
        };
        "dto.CreateLeadInput": {
            business_field?: string;
            capacity_mbps?: number;
            city_id?: number;
            company_name: string;
            district_id?: number;
            email?: string;
            existing_isp?: string;
            forecast_mrr?: number;
            lead_source_id?: string;
            mobile_phone?: string;
            office_phone?: string;
            other_services?: string;
            owner_id?: string;
            pic_name?: string;
            pic_position?: string;
            price?: number;
            province_id?: number;
            rt?: string;
            rw?: string;
            service_type_id?: string;
            street?: string;
            village_id?: number;
            website?: string;
            zip_id?: number;
        };
        "dto.CreateLeadSourceInput": {
            name: string;
        };
        "dto.CreateServiceTypeInput": {
            name: string;
        };
        "dto.CreateTeamInput": {
            name: string;
        };
        "dto.CreateUserInput": {
            email: string;
            name: string;
            password: string;
            /** @enum {string} */
            role: "SALES" | "LEADER" | "ADMIN_SALES" | "SU";
            team_id?: string;
        };
        "dto.DashboardActivityResponse": {
            buckets?: components["schemas"]["dto.ActivityBucket"][];
        };
        "dto.DashboardSalesActivityResponse": {
            items?: components["schemas"]["dto.SalesActivityRow"][];
        };
        "dto.DashboardSegmentsResponse": {
            any_survey?: boolean;
            business_fields?: components["schemas"]["dto.SegmentRow"][];
            competitor?: components["schemas"]["dto.CompetitorStats"];
            isps?: components["schemas"]["dto.IspRow"][];
            regions?: components["schemas"]["dto.RegionRow"][];
            sources?: components["schemas"]["dto.SegmentRow"][];
        };
        "dto.DashboardStaleLeadsResponse": {
            items?: components["schemas"]["dto.StaleLeadRow"][];
        };
        "dto.DashboardSummaryResponse": {
            follow_up?: components["schemas"]["dto.MetricCard"];
            funnel?: components["schemas"]["dto.FunnelResponse"];
            lead_baru?: components["schemas"]["dto.MetricCard"];
            survey?: components["schemas"]["dto.MetricCard"];
            terlantar?: components["schemas"]["dto.MetricCard"];
            total_forecast_mrr?: number;
        };
        "dto.DeactivateUserInput": {
            reassign_to_user_id?: string;
        };
        "dto.DistrictResponse": {
            id?: number;
            name?: string;
        };
        "dto.FollowUpResponse": {
            created_at?: string;
            created_by_id?: string;
            created_by_name?: string;
            id?: string;
            lead_id?: string;
            note?: string;
        };
        "dto.FunnelResponse": {
            baru_to_fu_pct?: number;
            fu_to_survey_pct?: number;
            lost_count?: number;
            lost_pct?: number;
            stages?: components["schemas"]["dto.FunnelStage"][];
        };
        "dto.FunnelStage": {
            count?: number;
            name?: string;
            pct?: number;
        };
        "dto.IspRow": {
            count?: number;
            name?: string;
        };
        "dto.LeadDetailResponse": {
            business_field?: string;
            capacity_mbps?: number;
            city_id?: number;
            city_name?: string;
            code?: string;
            company_name?: string;
            created_at?: string;
            created_by_id?: string;
            created_by_name?: string;
            district_id?: number;
            district_name?: string;
            email?: string;
            existing_isp?: string;
            follow_up_count?: number;
            forecast_mrr?: number;
            id?: string;
            is_stale?: boolean;
            last_follow_up_at?: string;
            lead_source_id?: string;
            lead_source_name?: string;
            lost_reason?: string;
            mobile_phone?: string;
            office_phone?: string;
            other_services?: string;
            owner_id?: string;
            owner_name?: string;
            owner_team_name?: string;
            pic_name?: string;
            pic_position?: string;
            price?: number;
            province_id?: number;
            province_name?: string;
            rt?: string;
            rw?: string;
            service_type_id?: string;
            service_type_name?: string;
            status?: string;
            street?: string;
            village_id?: number;
            village_name?: string;
            website?: string;
            zip_code?: string;
            zip_id?: number;
        };
        "dto.LeadResponse": {
            business_field?: string;
            capacity_mbps?: number;
            city_id?: number;
            city_name?: string;
            code?: string;
            company_name?: string;
            created_at?: string;
            created_by_id?: string;
            district_id?: number;
            email?: string;
            existing_isp?: string;
            follow_up_count?: number;
            forecast_mrr?: number;
            id?: string;
            is_stale?: boolean;
            last_follow_up_at?: string;
            lead_source_id?: string;
            lost_reason?: string;
            mobile_phone?: string;
            office_phone?: string;
            other_services?: string;
            owner_id?: string;
            owner_name?: string;
            owner_team_name?: string;
            pic_name?: string;
            pic_position?: string;
            price?: number;
            province_id?: number;
            rt?: string;
            rw?: string;
            service_type_id?: string;
            status?: string;
            street?: string;
            village_id?: number;
            website?: string;
            zip_id?: number;
        };
        "dto.LeadSourceAdminResponse": {
            created_at?: string;
            id?: string;
            is_active?: boolean;
            name?: string;
        };
        "dto.LeadSourceResponse": {
            id?: string;
            name?: string;
        };
        "dto.LoginInput": {
            email: string;
            password: string;
        };
        "dto.MetricCard": {
            change_pct?: number;
            value?: number;
        };
        "dto.PaginatedLeadResponse": {
            items?: components["schemas"]["dto.LeadResponse"][];
            limit?: number;
            page?: number;
            total?: number;
        };
        "dto.ProvinceResponse": {
            code?: string;
            id?: number;
            name?: string;
        };
        "dto.RefreshTokenInput": {
            refresh_token?: string;
        };
        "dto.RegionRow": {
            lead_count?: number;
            /** @description "province" | "city" */
            level?: string;
            name?: string;
            parent?: string;
            survey_count?: number;
        };
        "dto.ResetPasswordInput": {
            new_password: string;
        };
        "dto.SalesActivityRow": {
            attention_tag?: string;
            avg_fu_per_lead?: number;
            conv_pct?: number;
            follow_up?: number;
            forecast_mrr?: number;
            last_activity?: string;
            lead_baru?: number;
            name?: string;
            survey?: number;
            team_name?: string;
            terlantar?: number;
            user_id?: string;
        };
        "dto.SegmentRow": {
            conversion_pct?: number;
            count?: number;
            name?: string;
            warn?: boolean;
        };
        "dto.ServiceTypeAdminResponse": {
            created_at?: string;
            id?: string;
            is_active?: boolean;
            name?: string;
        };
        "dto.ServiceTypeResponse": {
            id?: string;
            name?: string;
        };
        "dto.StaleLeadRow": {
            code?: string;
            company_name?: string;
            days_since?: number;
            owner_name?: string;
        };
        "dto.TeamResponse": {
            created_at?: string;
            id?: string;
            is_active?: boolean;
            name?: string;
        };
        "dto.TokenResponse": {
            access_token?: string;
            refresh_token?: string;
            user?: components["schemas"]["dto.UserResponse"];
        };
        "dto.UpdateLeadInput": {
            business_field?: string;
            capacity_mbps?: number;
            city_id?: number;
            company_name?: string;
            district_id?: number;
            email?: string;
            existing_isp?: string;
            forecast_mrr?: number;
            lead_source_id?: string;
            mobile_phone?: string;
            office_phone?: string;
            other_services?: string;
            owner_id?: string;
            pic_name?: string;
            pic_position?: string;
            price?: number;
            province_id?: number;
            rt?: string;
            rw?: string;
            service_type_id?: string;
            street?: string;
            village_id?: number;
            website?: string;
            zip_id?: number;
        };
        "dto.UpdateLeadSourceInput": {
            is_active?: boolean;
            name?: string;
        };
        "dto.UpdateLeadStatusInput": {
            lost_reason?: string;
            /** @enum {string} */
            status: "FOLLOW_UP" | "SURVEY" | "SALES_CONFIRMATION" | "REGISTRASI" | "INSTALASI" | "TRIAL" | "INVOICE_BULANAN" | "LOST";
        };
        "dto.UpdateProfileInput": {
            name: string;
        };
        "dto.UpdateServiceTypeInput": {
            is_active?: boolean;
            name?: string;
        };
        "dto.UpdateTeamInput": {
            is_active?: boolean;
            name?: string;
        };
        "dto.UpdateUserInput": {
            /**
             * @description IsActive, when true, reactivates a previously deactivated user. false
             *     is rejected by the service — deactivation only happens through
             *     POST /users/:id/deactivate, which carries the active-lead-reassignment
             *     and last-active-administrator safety checks this endpoint doesn't.
             */
            is_active?: boolean;
            name?: string;
            /** @enum {string} */
            role?: "SALES" | "LEADER" | "ADMIN_SALES" | "SU";
            team_id?: string;
        };
        "dto.UserResponse": {
            created_at?: string;
            email?: string;
            id?: string;
            is_active?: boolean;
            name?: string;
            role?: string;
            team_id?: string;
            team_name?: string;
        };
        "dto.VillageResponse": {
            id?: number;
            name?: string;
            zip?: components["schemas"]["dto.ZipResponse"];
        };
        "dto.ZipResponse": {
            code?: string;
            id?: number;
        };
        "utils.Response": {
            data?: unknown;
            errors?: unknown;
            message?: string;
            success?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
