//go:build integration

package repository

import (
	"fiber-api-boilerplate/internal/models"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
)

func TestUserRepository_Create(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	user := &models.User{
		Email:    "test@test.com",
		Password: "hashed",
		Name:     "Test",
		Role:     "SU",
	}

	err := repo.Create(user)

	assert.NoError(t, err)
	assert.NotEmpty(t, user.ID) // UUID v7 generated by BeforeCreate hook
}

func TestUserRepository_FindByEmail_Found(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	user := &models.User{
		Email:    "test@test.com",
		Password: "hashed",
		Name:     "Test",
		Role:     "SU",
	}
	db.Create(user)

	found, err := repo.FindByEmail("test@test.com")

	assert.NoError(t, err)
	assert.Equal(t, "test@test.com", found.Email)
}

func TestUserRepository_FindByEmail_PreloadsTeam(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)
	teamRepo := NewSalesTeamRepository(db)

	team := &models.SalesTeam{Name: "Tim Utara"}
	require.NoError(t, teamRepo.Create(team))

	user := &models.User{
		Name: "Test Sales", Email: "sales-team-preload-email@test.com", Password: "hashed",
		Role: "SALES", TeamID: &team.ID, IsActive: true,
	}
	require.NoError(t, repo.Create(user))

	found, err := repo.FindByEmail("sales-team-preload-email@test.com")
	assert.NoError(t, err)
	if assert.NotNil(t, found.Team) {
		assert.Equal(t, "Tim Utara", found.Team.Name)
	}
}

func TestUserRepository_FindByEmail_NotFound(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	_, err := repo.FindByEmail("nonexistent@test.com")

	assert.ErrorIs(t, err, gorm.ErrRecordNotFound)
}

func TestUserRepository_FindByID(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	user := &models.User{
		Email:    "test@test.com",
		Password: "hashed",
		Name:     "Test",
		Role:     "SU",
	}
	db.Create(user)

	found, err := repo.FindByID(user.ID)

	assert.NoError(t, err)
	assert.Equal(t, user.ID, found.ID)
}

func TestUserRepository_FindByID_PreloadsTeam(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)
	teamRepo := NewSalesTeamRepository(db)

	team := &models.SalesTeam{Name: "Tim Utara"}
	require.NoError(t, teamRepo.Create(team))

	user := &models.User{
		Name: "Test Sales", Email: "sales-team-preload@test.com", Password: "hashed",
		Role: "SALES", TeamID: &team.ID, IsActive: true,
	}
	require.NoError(t, repo.Create(user))

	found, err := repo.FindByID(user.ID)
	assert.NoError(t, err)
	if assert.NotNil(t, found.Team) {
		assert.Equal(t, "Tim Utara", found.Team.Name)
	}
}

func TestUserRepository_Update(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	user := &models.User{
		Email:    "test@test.com",
		Password: "hashed",
		Name:     "Old Name",
		Role:     "SU",
	}
	db.Create(user)

	user.Name = "New Name"
	err := repo.Update(user)

	assert.NoError(t, err)

	found, _ := repo.FindByID(user.ID)
	assert.Equal(t, "New Name", found.Name)
}

func TestUserRepository_List(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	db.Create(&models.User{Email: "a@test.com", Password: "h", Name: "A", Role: "SU"})
	db.Create(&models.User{Email: "b@test.com", Password: "h", Name: "B", Role: "SU"})

	users, err := repo.List()

	assert.NoError(t, err)
	assert.Len(t, users, 2)
}

func TestUserRepository_ListWithFilter(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	team := &models.SalesTeam{Name: "Team A"}
	db.Create(team)

	db.Create(&models.User{Email: "sales@test.com", Password: "h", Name: "Sales", Role: "SALES", TeamID: &team.ID})
	db.Create(&models.User{Email: "su@test.com", Password: "h", Name: "SU", Role: "SU"})
	db.Create(&models.User{Email: "leader@test.com", Password: "h", Name: "Leader", Role: "LEADER", TeamID: &team.ID})

	// Test single role (regression: existing behavior must not change)
	byRole, err := repo.ListWithFilter("SALES", "")
	assert.NoError(t, err)
	require.Len(t, byRole, 1)
	assert.Equal(t, "sales@test.com", byRole[0].Email)

	// Test comma-separated roles
	byMultipleRoles, err := repo.ListWithFilter("SALES,LEADER", "")
	assert.NoError(t, err)
	require.Len(t, byMultipleRoles, 2)
	emails := map[string]bool{byMultipleRoles[0].Email: true, byMultipleRoles[1].Email: true}
	assert.True(t, emails["sales@test.com"])
	assert.True(t, emails["leader@test.com"])

	// Test comma-separated roles with whitespace and empty elements
	byMultipleRolesWithSpaces, err := repo.ListWithFilter("SALES, ,LEADER", "")
	assert.NoError(t, err)
	require.Len(t, byMultipleRolesWithSpaces, 2)
	emailsWithSpaces := map[string]bool{byMultipleRolesWithSpaces[0].Email: true, byMultipleRolesWithSpaces[1].Email: true}
	assert.True(t, emailsWithSpaces["sales@test.com"])
	assert.True(t, emailsWithSpaces["leader@test.com"])

	// Test comma-only (all empty elements, no role filter applied)
	noRoleFilter, err := repo.ListWithFilter(",", "")
	assert.NoError(t, err)
	assert.Len(t, noRoleFilter, 3)

	// Test by team (existing regression check)
	byTeam, err := repo.ListWithFilter("", team.ID.String())
	assert.NoError(t, err)
	require.Len(t, byTeam, 2)
	teamEmails := map[string]bool{byTeam[0].Email: true, byTeam[1].Email: true}
	assert.True(t, teamEmails["sales@test.com"])
	assert.True(t, teamEmails["leader@test.com"])

	// Test no filters (existing regression check)
	all, err := repo.ListWithFilter("", "")
	assert.NoError(t, err)
	assert.Len(t, all, 3)
}

func TestUserRepository_CountActiveByOwner(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	owner := &models.User{Email: "owner@test.com", Password: "h", Name: "Owner", Role: "SU"}
	db.Create(owner)
	otherOwner := &models.User{Email: "other@test.com", Password: "h", Name: "Other", Role: "SU"}
	db.Create(otherOwner)

	lostReason := "budget"

	// two active leads (BARU, FOLLOW_UP) for owner
	assert.NoError(t, db.Create(&models.Lead{Code: "LD-2607-0001", Status: "BARU", OwnerID: owner.ID, CreatedByID: owner.ID, CompanyName: "Co A"}).Error)
	assert.NoError(t, db.Create(&models.Lead{Code: "LD-2607-0002", Status: "FOLLOW_UP", OwnerID: owner.ID, CreatedByID: owner.ID, CompanyName: "Co B"}).Error)
	// terminal leads for owner - must not be counted
	assert.NoError(t, db.Create(&models.Lead{Code: "LD-2607-0003", Status: "LOST", LostReason: &lostReason, OwnerID: owner.ID, CreatedByID: owner.ID, CompanyName: "Co C"}).Error)
	assert.NoError(t, db.Create(&models.Lead{Code: "LD-2607-0004", Status: "HANDOFF_ODOO", OwnerID: owner.ID, CreatedByID: owner.ID, CompanyName: "Co D"}).Error)
	// active lead for a different owner - must not be counted
	assert.NoError(t, db.Create(&models.Lead{Code: "LD-2607-0005", Status: "BARU", OwnerID: otherOwner.ID, CreatedByID: otherOwner.ID, CompanyName: "Co E"}).Error)

	count, err := repo.CountActiveByOwner(owner.ID)

	assert.NoError(t, err)
	assert.Equal(t, int64(2), count)
}

func TestUserRepository_ReassignOwner(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	oldOwner := &models.User{Email: "old@test.com", Password: "h", Name: "Old", Role: "SU"}
	db.Create(oldOwner)
	newOwner := &models.User{Email: "new@test.com", Password: "h", Name: "New", Role: "SU"}
	db.Create(newOwner)
	untouchedOwner := &models.User{Email: "untouched@test.com", Password: "h", Name: "Untouched", Role: "SU"}
	db.Create(untouchedOwner)

	lead1 := &models.Lead{Code: "LD-2607-0006", Status: "BARU", OwnerID: oldOwner.ID, CreatedByID: oldOwner.ID, CompanyName: "Co F"}
	lead2 := &models.Lead{Code: "LD-2607-0007", Status: "FOLLOW_UP", OwnerID: oldOwner.ID, CreatedByID: oldOwner.ID, CompanyName: "Co G"}
	untouchedLead := &models.Lead{Code: "LD-2607-0008", Status: "BARU", OwnerID: untouchedOwner.ID, CreatedByID: untouchedOwner.ID, CompanyName: "Co H"}
	assert.NoError(t, db.Create(lead1).Error)
	assert.NoError(t, db.Create(lead2).Error)
	assert.NoError(t, db.Create(untouchedLead).Error)

	err := repo.ReassignOwner(oldOwner.ID, newOwner.ID)

	assert.NoError(t, err)

	var reassignedCount int64
	db.Model(&models.Lead{}).Where("owner_id = ?", newOwner.ID).Count(&reassignedCount)
	assert.Equal(t, int64(2), reassignedCount)

	var oldOwnerCount int64
	db.Model(&models.Lead{}).Where("owner_id = ?", oldOwner.ID).Count(&oldOwnerCount)
	assert.Equal(t, int64(0), oldOwnerCount)

	var untouched models.Lead
	db.First(&untouched, "id = ?", untouchedLead.ID)
	assert.Equal(t, untouchedOwner.ID, untouched.OwnerID)
}
