//go:build integration

package repository

import (
	"fiber-api-boilerplate/internal/models"
	"testing"

	"github.com/stretchr/testify/assert"
	"gorm.io/gorm"
)

func TestUserRepository_Create(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	user := &models.User{
		Email:    "test@test.com",
		Password: "hashed",
		Name:     "Test",
		Role:     "SU",
	}

	err := repo.Create(user)

	assert.NoError(t, err)
	assert.NotEmpty(t, user.ID) // UUID v7 generated by BeforeCreate hook
}

func TestUserRepository_FindByEmail_Found(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	user := &models.User{
		Email:    "test@test.com",
		Password: "hashed",
		Name:     "Test",
		Role:     "SU",
	}
	db.Create(user)

	found, err := repo.FindByEmail("test@test.com")

	assert.NoError(t, err)
	assert.Equal(t, "test@test.com", found.Email)
}

func TestUserRepository_FindByEmail_NotFound(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	_, err := repo.FindByEmail("nonexistent@test.com")

	assert.ErrorIs(t, err, gorm.ErrRecordNotFound)
}

func TestUserRepository_FindByID(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	user := &models.User{
		Email:    "test@test.com",
		Password: "hashed",
		Name:     "Test",
		Role:     "SU",
	}
	db.Create(user)

	found, err := repo.FindByID(user.ID)

	assert.NoError(t, err)
	assert.Equal(t, user.ID, found.ID)
}

func TestUserRepository_Update(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	user := &models.User{
		Email:    "test@test.com",
		Password: "hashed",
		Name:     "Old Name",
		Role:     "SU",
	}
	db.Create(user)

	user.Name = "New Name"
	err := repo.Update(user)

	assert.NoError(t, err)

	found, _ := repo.FindByID(user.ID)
	assert.Equal(t, "New Name", found.Name)
}

func TestUserRepository_List(t *testing.T) {
	db := setupTestDB(t)
	repo := NewUserRepository(db)

	db.Create(&models.User{Email: "a@test.com", Password: "h", Name: "A", Role: "SU"})
	db.Create(&models.User{Email: "b@test.com", Password: "h", Name: "B", Role: "SU"})

	users, err := repo.List()

	assert.NoError(t, err)
	assert.Len(t, users, 2)
}
